trigger:
  batch: true
  branches:
    include:
      - ops/wei-pipeline
  paths:
    include:
      - test-pipeline

pr:
  autoCancel: false
  branches:
    include:
      # - main
      - test-pipeline
  paths:
    include:
      - test-pipeline
variables:
  - name: yuhuipipeline
    value: $[or(eq(variables['System.PullRequest.SourceBranch'], 'test-pipeline'), eq(variables['Build.SourceBranch'], 'refs/heads/test-pipeline'))]


  
